# Generated by Django 4.1.3 on 2022-12-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="money",
            new_name="price",
        ),
    ]
