# Generated by Django 4.1.3 on 2022-12-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_rename_money_payment_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="price",
            new_name="money_to_pay",
        ),
    ]
