# Generated by Django 4.1.3 on 2022-11-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="days_to_return",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
