# Generated by Django 4.1.3 on 2022-12-01 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_alter_borrowing_expected_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='expected_return_date',
            field=models.DateField(default=datetime.date(2022, 12, 11), null=True),
        ),
    ]
